image: clever/drone-go:1.5
notify:
  email:
    recipients:
      - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: "shorty"
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    username: $$docker_username
    password: $$docker_password
    image_name: clever/shorty
    registry_login: true
    tags:
      - $(git rev-parse --short HEAD)
    when:
      branch: master
services:
- postgres
- redis
script:
- sudo apt-get install -y postgresql-client
- bash integration_tests.sh
- make build
